### ISSUE TITLE
NameError: wrong constant name Attributes::Attribute, when parsing a serialized ActiveRecord object

### ISSUE THREAD

**Issue by charl** [ohler55/ox#116]
I have a Device (ActiveRecord) object that is embedded in an Interface ( ActiveAttr) object. When I try to deserialize the ActiveAttr model it blows up with:

```ruby
[24] pry(main)> ox_o = Ox.dump(interface, :indent => 2, :circular => true, :effort => :strict); oo = Ox.parse_obj ox_o
NameError: wrong constant name Attributes::Attribute
from /home/charl/.rvm/gems/ruby-2.2.2@manage.oneconfig.net/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:390:in `const_defined?'
```

Not using _:circular => true_ results in:

```ruby
[26] pry(main)> ox_o = Ox.dump(interface, :indent => 2, :circular => false, :effort => :strict)
SystemStackError: maximum depth exceeded
from (pry):12:in `dump'
```

If I delete the reference to the Device from the interface it deserializes fine:

```ruby
[31] pry(main)> interface.device = nil
=> nil
[32] pry(main)> ox_o = Ox.dump(interface, :indent => 2, :circular => true, :effort => :strict); oo = Ox.parse_obj ox_o
=> #<Interface address_family_name: "", admin_status: "Up", category: "ifl", description: "", device: nil, id: "b59141fac04293e340cfd7078e36fb57", ifa_local: [], ifd: "ge-4/0/0", name: "ge-4/0/0.0", operational_status: "Up", port_mode: "", type: nil, units: [], vlan_tagging: false, vlans: []>
```

The serialized Device's XML looks like this (I have removed some sensitive bits):

```xml
<o c="Device" i="1">
  <h a="@attributes" i="2">
    <s i="3">id</s>
    <i>382</i>
    <s i="4">company_id</s>
    <i>236</i>
    <s i="15">created_at</s>
    <t>1426630675.000000000</t>
    <s i="16">updated_at</s>
    <t>1426630675.000000000</t>
    <s i="27">deleted_at</s>
    <z/>
    <s i="38">serials</s>
    <s i="39">null</s>
  </h>
  <z a="@relation"/>
  <h a="@changed_attributes" i="40">
  </h>
  <h a="@previously_changed" i="47"/>
  <h a="@attributes_cache" i="48">
    <s i="49">created_at</s>
    <o c="ActiveSupport::TimeWithZone" i="50">
      <z a="@time"/>
      <o a="@time_zone" c="ActiveSupport::TimeZone" i="51">
        <s a="@name" i="52">UTC</s>
        <z a="@utc_offset"/>
        <o a="@tzinfo" c="TZInfo::TimezoneProxy" i="53">
          <s a="@identifier" i="54">Etc/UTC</s>
          <z a="@real_timezone"/>
        </o>
        <z a="@current_period"/>
      </o>
      <t a="@utc">1426630675.000000000</t>
      <z a="@period"/>
    </o>
    <s i="55">updated_at</s>
    <o c="ActiveSupport::TimeWithZone" i="56">
      <z a="@time"/>
      <p a="@time_zone" i="51"/>
      <t a="@utc">1426630675.000000000</t>
      <z a="@period"/>
    </o>
    <s i="57">deleted_at</s>
    <z/>
  </h>
  <h a="@association_cache" i="58">
    <m>company</m>
    <o c="ActiveRecord::Associations::BelongsToAssociation" i="59">
      <o a="@target" c="Company" i="60">
        <h a="@attributes" i="61">
          <s i="62">id</s>
          <i>236</i>
          <s i="67">created_at</s>
          <t>1425251293.000000000</t>
          <s i="68">updated_at</s>
          <t>1425251293.000000000</t>
          <s i="77">extended_address</s>
          <z/>
          <s i="86">ancestry</s>
          <s i="87">1/210</s>
          <s i="88">deleted_at</s>
          <z/>
        </h>
        <z a="@relation"/>
        <h a="@changed_attributes" i="92"/>
        <h a="@previously_changed" i="93"/>
        <h a="@attributes_cache" i="94"/>
        <h a="@association_cache" i="95"/>
        <h a="@aggregation_cache" i="96"/>
        <n a="@marked_for_destruction"/>
        <n a="@destroyed"/>
        <n a="@readonly"/>
        <n a="@new_record"/>
        <m a="@primary_key_type">integer</m>
      </o>
      <o a="@reflection" c="ActiveRecord::Reflection::AssociationReflection" i="97">
        <m a="@macro">belongs_to</m>
        <m a="@name">company</m>
        <h a="@options" i="98"/>
        <c a="@active_record" c="Device"/>
        <s a="@plural_name" i="99">companies</s>
        <n a="@collection"/>
        <s a="@foreign_key" i="100">company_id</s>
        <s a="@class_name" i="101">Company</s>
        <c a="@klass" c="Company"/>
        <z a="@type"/>
      </o>
      <p a="@owner" i="1"/>
      <n a="@updated"/>
      <y a="@loaded"/>
      <s a="@stale_state" i="102">236</s>
      <o a="@association_scope" c="ActiveRecord::Relation" i="103">
        <o a="@table" c="Arel::Table" i="104">
          <s a="@name" i="105">companies</s>
          <c a="@engine" c="Company"/>
          <z a="@columns"/>
          <a a="@aliases" i="106"/>
          <z a="@table_alias"/>
          <z a="@primary_key"/>
        </o>
        <c a="@klass" c="Company"/>
        <z a="@implicit_readonly"/>
        <z a="@loaded"/>
        <n a="@default_scoped"/>
        <z a="@limit_value"/>
        <z a="@offset_value"/>
        <z a="@lock_value"/>
        <z a="@readonly_value"/>
        <z a="@from_value"/>
        <z a="@reordering_value"/>
        <z a="@reverse_order_value"/>
        <z a="@uniq_value"/>
        <a a="@includes_values" i="107"/>
        <a a="@eager_load_values" i="108"/>
        <a a="@preload_values" i="109"/>
        <a a="@select_values" i="110"/>
        <a a="@group_values" i="111"/>
        <a a="@order_values" i="112"/>
        <a a="@joins_values" i="113"/>
        <a a="@where_values" i="114">
          <o c="Arel::Nodes::Equality" i="115">
            <u a="@left" c="Arel::Attributes::Attribute" i="116">
              <o a="0" c="Arel::Table" i="117">
                <p a="@name" i="105"/>
                <c a="@engine" c="ActiveRecord::Base"/>
                <z a="@columns"/>
                <a a="@aliases" i="118"/>
                <z a="@table_alias"/>
                <z a="@primary_key"/>
              </o>
              <s a="1" i="119">id</s>
            </u>
            <i a="@right">236</i>
          </o>
        </a>
        <a a="@having_values" i="120"/>
        <a a="@bind_values" i="121"/>
        <a a="@extensions" i="122"/>
        <h a="@create_with_value" i="123"/>
        <o a="@arel" c="Arel::SelectManager" i="124">
          <c a="@engine" c="Company"/>
          <o a="@ctx" c="Arel::Nodes::SelectCore" i="125">
            <o a="@source" c="Arel::Nodes::JoinSource" i="126">
              <p a="@left" i="104"/>
              <a a="@right" i="127"/>
            </o>
            <z a="@top"/>
            <z a="@set_quantifier"/>
            <a a="@projections" i="128">
              <u c="Arel::Attributes::Attribute" i="129">
                <p a="0" i="104"/>
                <s a="1" i="130">*</s>
              </u>
            </a>
            <a a="@wheres" i="131">
              <o c="Arel::Nodes::And" i="132">
                <a a="@children" i="133">
                  <p i="115"/>
                </a>
              </o>
            </a>
            <a a="@groups" i="134"/>
            <z a="@having"/>
            <a a="@windows" i="135"/>
          </o>
          <o a="@ast" c="Arel::Nodes::SelectStatement" i="136">
            <a a="@cores" i="137">
              <p i="125"/>
            </a>
            <a a="@orders" i="138"/>
            <z a="@limit"/>
            <z a="@lock"/>
            <z a="@offset"/>
            <z a="@with"/>
          </o>
        </o>
        <z a="@scope_for_create"/>
        <z a="@order_clause"/>
        <z a="@to_sql"/>
        <z a="@last"/>
        <z a="@first"/>
        <z a="@join_dependency"/>
        <z a="@should_eager_load"/>
        <a a="@records" i="139"/>
      </o>
    </o>
  </h>
  <h a="@aggregation_cache" i="140"/>
  <n a="@marked_for_destruction"/>
  <n a="@destroyed"/>
  <n a="@readonly"/>
  <n a="@new_record"/>
  <a a="@interfaces" i="141"/>
</o>
```

When you try deserialize the XML back to an object you get:

```ruby
[60] pry(main)> Ox.parse_obj ox_o
NameError: wrong constant name Attributes::Attribute
from /home/charl/.rvm/gems/ruby-2.2.2@manage.oneconfig.net/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:390:in `const_defined?'
```

If you remove the _association_cache_ hierarchy that has the only two matches for _'Attributes::Attribute'_ the device object is deserialized fine:

```ruby
[67] pry(main)> Ox.parse_obj ox_o
=> #<Device id: 382, company_id: 236, created_at: "2015-03-17 22:17:55", updated_at: "2015-03-17 22:17:55", deleted_at: nil, serials: "null">
```

I am testing with:

* rails 3.2.18
* activerecord 3.2.18
* ox 2.2.0

**Comment by ohler55** [comment]
From you description is sounds like there are circular references. That is why circular must be true. Lets focus on the Attributes::Attribute. Can you create an instance of Arel::Attributes::Attribute or check that it is defined? The error message indicates the class does not exist in the environment being used to deserialize.

**Comment by charl** [comment]
You are of courtse right:

```ruby
[13] pry(main)> o.device.arel
NoMethodError: undefined method `arel' for #<Device:0x00000005323110>
from /home/charl/.rvm/gems/ruby-2.2.2@manage.oneconfig.net/gems/activemodel-3.2.18/lib/active_model/attribute_methods.rb:407:in `method_missing'
[14] pry(main)> o.device.arel
o.device.arel                    o.device.arel_attributes_values  
[14] pry(main)> o.device.arel_attributes_values
NoMethodError: protected method `arel_attributes_values' called for #<Device:0x00000005323110>
```

I was trying to use Ox as a drop in replacement for Marshal which works fine with the same data.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by charl** [comment]
There is still some issue her but I have moved on.
