### ISSUE TITLE
gem does not compile with truffle-ruby

### ISSUE THREAD

**Issue by topofocus** [ohler55/ox#231]
Hi,
experimenting with truffleruby (graalVM)

This is the output of bundle install:

```
Fetching ox 2.10.0
Installing ox 2.10.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox
/home/ubuntu/graalvm/jre/languages/ruby/bin/truffleruby -I /home/ubuntu/graalvm/jre/languages/ruby/lib/mri -r
./siteconf20190522-11854-fwvnd.rb extconf.rb
>>>>> Creating Makefile for truffleruby version 2.6.2 on x86_64-linux <<<<<
creating Makefile

current directory: /home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox
make "DESTDIR=" clean

current directory: /home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox
make "DESTDIR="
compiling base64.c
compiling builder.c
compiling cache.c
compiling cache8.c
compiling dump.c
compiling err.c
compiling gen_load.c
compiling hash_load.c
compiling obj_load.c
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:65:2: warning: implicit
declaration of function 'rb_enc_associate' is invalid in C99 [-Wimplicit-function-declaration]
        rb_enc_associate(rstr, (rb_encoding*)encoding);
        ^
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:65:38: error: expected
expression
        rb_enc_associate(rstr, (rb_encoding*)encoding);
                                            ^
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:65:26: error: use of
undeclared identifier 'rb_encoding'; did you mean 'encoding'?
        rb_enc_associate(rstr, (rb_encoding*)encoding);
                                ^~~~~~~~~~~
                                encoding
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:58:32: note: 'encoding'
declared here
str2sym(const char *str, void *encoding) {
                               ^
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:89:6: warning: implicit
declaration of function 'rb_enc_associate' is invalid in C99 [-Wimplicit-function-declaration]
            rb_enc_associate(rstr, (rb_encoding*)encoding);
            ^
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:89:42: error: expected
expression
            rb_enc_associate(rstr, (rb_encoding*)encoding);
                                                ^
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:89:30: error: use of
undeclared identifier 'rb_encoding'; did you mean 'encoding'?
            rb_enc_associate(rstr, (rb_encoding*)encoding);
                                    ^~~~~~~~~~~
                                    encoding
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0/ext/ox/obj_load.c:77:34: note: 'encoding'
declared here
name2var(const char *name, void *encoding) {
                                 ^
2 warnings and 4 errors generated.
make: *** [Makefile:214: obj_load.bc] Error 1

make failed, exit code 2

Gem files will remain installed in /home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/ox-2.10.0 for
inspection.
Results logged to
/home/ubuntu/graalvm/jre/languages/ruby/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ox-2.10.0/gem_make.out

```

any suggestion how to fix it?

**Comment by ohler55** [comment]
It looks like truffle Ruby does not support encoding. If you look in the `extconf.rb` there is a variable named `HAS_ENCODING_SUPPORT`. Set that to 0 with a conditional check or just hard code it. See if that works. If it does I can update the `extconf.rb` to check for truffle ruby.

**Comment by topofocus** [comment]
Thanks for the hint.

made the following assignments:

```
'HAS_ENCODING_SUPPORT' => 1,
'HAS_ONIG' => 1,
'HAS_PRIVATE_ENCODING' => 1,
```
The compilation runs with the following remarks

```
ubuntu@graal:~/ox/ext/ox$ ruby extconf.rb 
>>>>> Creating Makefile for truffleruby version 2.6.2 on x86_64-linux <<<<<
creating Makefile
ubuntu@graal:~/ox/ext/ox$ find . -name "*.rbc" -exec rm {} \;
ubuntu@graal:~/ox/ext/ox$ make
compiling base64.c
compiling builder.c
compiling cache.c
compiling cache8.c
compiling dump.c
/home/ubuntu/ox/ext/ox/dump.c:1197:10: warning: implicit declaration of function 'rb_str_ptr' is invalid in C99
      [-Wimplicit-function-declaration]
    ks = rb_str_ptr(rb_String(key));
         ^
1 warning generated.
compiling err.c
compiling gen_load.c
compiling hash_load.c
compiling obj_load.c
compiling ox.c
compiling parse.c
/home/ubuntu/ox/ext/ox/parse.c:1031:26: warning: implicit declaration of function 'rb_str_ptr' is invalid in C99
      [-Wimplicit-function-declaration]
                       0 == strcasecmp(rb_str_ptr(rb_String(ox_utf8_encoding)), rb_str_ptr(rb_String(pi->options->rb_enc)))) {
                                       ^
/home/ubuntu/ox/ext/ox/parse.c:1118:23: warning: implicit declaration of function 'rb_str_ptr' is invalid in C99
      [-Wimplicit-function-declaration]
                           0 == strcasecmp(rb_str_ptr(rb_String(ox_utf8_encoding)), rb_str_ptr(rb_String(pi->options->rb_enc)))) {
                                           ^
2 warnings generated.
compiling sax.c
compiling sax_as.c
compiling sax_buf.c
compiling sax_hint.c
compiling special.c
linking shared-object ox.su
ubuntu@graal:~/ox/ext/ox$ 
```

but the test fails:
```
Started
...F
===============================================================================
Failure: test_array_multi(Func)
./tests.rb:1764:in `dump_and_load'
./tests.rb:660:in `test_array_multi'
     657:     if RUBY_VERSION.start_with?('1.8')
     658:       dump_and_load([nil, true, false, 3, 'z', 7.9, 'a&b', :xyz, t], false)
     659:     else
  => 660:       dump_and_load([nil, true, false, 3, 'z', 7.9, 'a&b', :xyz, t, (-1..7)], false)
     661:     end
     662:   end
     663: 
<[nil, true, false, 3, "z", 7.9, "a&b", :xyz, 2012-01-05 23:58:07 +0000, -1..7]> expected but was
<[nil, true, false, 3, "z", 7.9, "a&b", :xyz, 2012-01-05 23:58:07 +0000, nil..]>

diff:
? [nil, true, false, 3, "z", 7.9, "a&b", :xyz, 2012-01-05 23:58:07 +0000, -1 ..7]
?                                                                         nil    
===============================================================================
.F
===============================================================================
Failure: test_bad_class(Func)
./tests.rb:279:in `test_bad_class'
     276:   <i a="@x">3</i>
     277: </o>
     278: }
  => 279:     assert_raise(Ox::ParseError) {
     280:       Ox.load(xml, :mode => :object, :trace => 0)
     281:     }
     282:   end

<Ox::ParseError> expected but was
<RuntimeError(<External function @ruby_vsnprintf cannot be found. (LLVMLinkerException)
Translated to internal error>)>

diff:
+ RuntimeError(<External function @ruby_vsnprintf cannot be found. (LLVMLinkerException)
? Ox::Pa               rs   eError  
? Tr    nslated to inte nal       >)
===============================================================================
F
===============================================================================
Failure: test_bad_format(Func)
./tests.rb:649:in `test_bad_format'
     646:   def test_bad_format
     647:     Ox::default_options = $ox_object_options
     648:     xml = "<?xml version=\"1.0\"?>\n<tag>test</tagz>\n"
  => 649:     assert_raise(Ox::ParseError) {
     650:       Ox.load(xml, :mode => :generic, :trace => 0)
     651:     }
     652:   end

<Ox::ParseError> expected but was
<RuntimeError(<External function @ruby_vsnprintf cannot be found. (LLVMLinkerException)
Translated to internal error>)>

diff:
+ RuntimeError(<External function @ruby_vsnprintf cannot be found. (LLVMLinkerException)
? Ox::Pa               rs   eError  
? Tr    nslated to inte nal       >)
===============================================================================
..E
===============================================================================
Error: test_big_dtd(Func): NoMethodError: undefined method `encoding' for nil:NilClass
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:68:in `block in get_encoding_from_native'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:67:in `synchronize'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:67:in `get_encoding_from_native'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:1799:in `rb_enc_from_native_encoding'
./src/main/c/cext/ruby.c:1247:in `rb_enc_from_encoding'
./src/main/c/cext/ruby.c:1318:in `rb_enc_to_index'
./src/main/c/cext/ruby.c:1213:in `rb_enc_associate'
/home/ubuntu/ox/ext/ox/gen_load.c:217:in `add_doctype'
/home/ubuntu/ox/ext/ox/parse.c:375:in `read_doctype'
/home/ubuntu/ox/ext/ox/parse.c:175:in `ox_parse'
/home/ubuntu/ox/ext/ox/ox.c:705:in `to_gen'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `parse'
./tests.rb:366:in `test_big_dtd'
     363:   def test_big_dtd
     364:     Ox::default_options = $ox_object_options
     365:     xml = %{<!DOCTYPE Objects [<!ELEMENT Objects (RentObjects)><!ENTITY euml "&#235;"><!ENTITY Atilde "&#195;">]>}
  => 366:     doc = Ox.parse(xml)
     367:     assert_equal(%{Objects [<!ELEMENT Objects (RentObjects)><!ENTITY euml "&#235;"><!ENTITY Atilde "&#195;">]}, doc.nodes[0].value)
     368:   end
     369: 
===============================================================================
E
===============================================================================
Error: test_bigdecimal(Func):
  RuntimeError: Index 0 out of bounds for length 0 (ArrayIndexOutOfBoundsException)
  	from com.oracle.truffle.object.ShapeImpl$DynamicObjectFactoryImpl.newInstance(ShapeImpl.java:1058)
  	from org.truffleruby.language.objects.AllocateObjectNode.allocate(AllocateObjectNode.java:150)
  	from org.truffleruby.language.objects.AllocateObjectNode.allocateCached(AllocateObjectNode.java:69)
  	from org.truffleruby.language.objects.AllocateObjectNodeGen.executeAndSpecialize(AllocateObjectNodeGen.java:135)
  	from org.truffleruby.language.objects.AllocateObjectNodeGen.executeAllocate(AllocateObjectNodeGen.java:83)
  	from org.truffleruby.language.objects.AllocateObjectNode.allocate(AllocateObjectNode.java:46)
  	from org.truffleruby.core.basicobject.BasicObjectNodes$AllocateNode.allocate(BasicObjectNodes.java:486)
  	from org.truffleruby.core.basicobject.BasicObjectNodesFactory$AllocateNodeFactory$AllocateNodeGen.executeAndSpecialize(BasicObjectNodesFactory.java:1556)
  	from org.truffleruby.core.basicobject.BasicObjectNodesFactory$AllocateNodeFactory$AllocateNodeGen.execute(BasicObjectNodesFactory.java:1548)
  	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
  Translated to internal error
ruby.c:1739:in `__allocate__'
./src/main/c/cext/ruby.c:1739:in `rb_obj_alloc'
/home/ubuntu/ox/ext/ox/obj_load.c:142:in `classname2obj'
/home/ubuntu/ox/ext/ox/obj_load.c:252:in `get_obj_from_attrs'
/home/ubuntu/ox/ext/ox/obj_load.c:665:in `add_element'
/home/ubuntu/ox/ext/ox/parse.c:481:in `read_element'
/home/ubuntu/ox/ext/ox/parse.c:187:in `ox_parse'
/home/ubuntu/ox/ext/ox/ox.c:860:in `load'
/home/ubuntu/ox/ext/ox/ox.c:943:in `load_str'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `load'
./tests.rb:1760:in `dump_and_load'
./tests.rb:218:in `test_bigdecimal'
     215:   def test_bigdecimal
     216:     Ox::default_options = $ox_object_options
     217:     bd = BigDecimal('7.123456789')
  => 218:     dump_and_load(bd, false)
     219:   end
     220: 
     221:   def test_complex_number
===============================================================================
.....E
===============================================================================
Error: test_builder_block_io(Func): NotImplementedError: fork is not available
./tests.rb:1511:in `fork'
./tests.rb:1511:in `block in test_builder_block_io'
     1508: 
     1509:   def test_builder_block_io
     1510:     IO.pipe do |r,w|
  => 1511:       if fork
     1512:         w.close
     1513:         xml = r.read(1000)
     1514:         xml.force_encoding('UTF-8')
./tests.rb:1510:in `pipe'
./tests.rb:1510:in `test_builder_block_io'
===============================================================================
.E
===============================================================================
Error: test_builder_io(Func): NotImplementedError: fork is not available
./tests.rb:1435:in `fork'
./tests.rb:1435:in `block in test_builder_io'
     1432: 
     1433:   def test_builder_io
     1434:     IO.pipe do |r,w|
  => 1435:       if fork
     1436:         w.close
     1437:         xml = r.read(1000)
     1438:         xml.force_encoding('UTF-8')
./tests.rb:1434:in `pipe'
./tests.rb:1434:in `test_builder_io'
===============================================================================
.....E
===============================================================================
Error: test_circular(Func):
  RuntimeError: External function @rb_str_ptr cannot be found. (LLVMLinkerException)
  Translated to internal error
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:1035:in `execute_without_conversion'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:1035:in `block in rb_hash_foreach'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:1034:in `each'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext.rb:1034:in `rb_hash_foreach'
./src/main/c/cext/ruby.c:1698:in `rb_hash_foreach'
/home/ubuntu/ox/ext/ox/dump.c:1092:in `dump_gen_element'
/home/ubuntu/ox/ext/ox/dump.c:870:in `dump_obj'
/home/ubuntu/ox/ext/ox/dump.c:648:in `dump_obj'
/home/ubuntu/ox/ext/ox/dump.c:1012:in `dump_var'
/home/ubuntu/ox/ext/ox/dump.c:903:in `dump_obj'
/home/ubuntu/ox/ext/ox/dump.c:589:in `dump_first_obj'
/home/ubuntu/ox/ext/ox/dump.c:1286:in `dump_obj_to_xml'
/home/ubuntu/ox/ext/ox/dump.c:1300:in `ox_write_obj_to_str'
/home/ubuntu/ox/ext/ox/ox.c:1295:in `dump'
/home/ubuntu/graalvm/jre/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `dump'
./tests.rb:1758:in `dump_and_load'
./tests.rb:740:in `test_circular'
     737:       a << h
     738:       a << e
     739:       a << b
  => 740:       loaded = dump_and_load(b, false, true)
     741:       # modify the string
     742:       loaded.instance_variable_get(:@s).gsub!(',', '_')
     743:       b.instance_variable_get(:@s).gsub!(',', '_')
===============================================================================

```

**Comment by ohler55** [comment]
Thats progress at least. It looks like Truffle Ruby is missing a few functions that regular ruby has. `fork` for example. `ruby_vsnprintf`and 'rb_str_ptr` are an odd ones though. They must be called by something inside the truffle code. `fork` is only used for the tests. Not sure about the others.

**Comment by ohler55** [comment]
Is there any reason this should remain open? I think the fix is in truffle ruby.
