### ISSUE TITLE
ox 2.14.0 test suite fails with ruby 3.0

### ISSUE THREAD

**Issue by mtasaka** [ohler55/ox#258]
With ox 2.14.0, test suite passes with ruby 2.7.2p137 but fails with ruby 3.0 like:

```
+ ruby -Ilib:test test/tests.rb
Loaded suite test/tests
Started
...E
===============================================================================
Error: test_array_multi(Func): FrozenError: can't modify frozen Range: 0..0
test/tests.rb:1801:in `load'
test/tests.rb:1801:in `dump_and_load'
test/tests.rb:691:in `test_array_multi'
     688:   def test_array_multi
     689:     Ox::default_options = $ox_object_options
     690:     t = Time.local(2012, 1, 5, 23, 58, 7)
  => 691:     dump_and_load([nil, true, false, 3, 'z', 7.9, 'a&b', :xyz, t, (-1..7)], false)
     692:   end
     693: 
     694:   def test_hash_multi
===============================================================================
..............
Finished in 0.009698967 seconds.
-------------------------------------------------------------------------------
16 tests, 32 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
93.75% passed
-------------------------------------------------------------------------------
1649.66 tests/s, 3299.32 assertions/s....
.
Finished in 0.011825445 seconds..
-------------------------------------------------------------------------------
18 tests, 34 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
94.4444% passed
-------------------------------------------------------------------------------
1522.14 tests/s, 2875.16 assertions/s.
..........................................................
E
===============================================================================
Error: test_hash_multi(Func): FrozenError: can't modify frozen Range: 0..0
test/tests.rb:1801:in `load'
test/tests.rb:1801:in `dump_and_load'
test/tests.rb:697:in `test_hash_multi'
     694:   def test_hash_multi
     695:     Ox::default_options = $ox_object_options
     696:     t = Time.local(2012, 1, 5, 23, 58, 7)
  => 697:     dump_and_load({ nil => nil, true => true, false => false, 3 => 3, 'z' => 'z', 7.9 => 7.9, 'a&b' => 'a&b', :xyz => :xyz, t => t, (-1..7) => (-1..7) }, false)
     698:   end
     699: 
     700:   def test_object_multi
===============================================================================
.................................E
===============================================================================
Error: test_object_multi(Func): FrozenError: can't modify frozen Range: 0..0
test/tests.rb:1801:in `load'
test/tests.rb:1801:in `dump_and_load'
test/tests.rb:703:in `test_object_multi'
     700:   def test_object_multi
     701:     Ox::default_options = $ox_object_options
     702:     t = Time.local(2012, 1, 5, 23, 58, 7)
  => 703:     dump_and_load(Bag.new(:@a => nil, :@b => true, :@c => false, :@d => 3, :@e => 'z', :@f => 7.9, :@g => 'a&b', :@h => :xyz, :@i => t, :@j => (-1..7)), false)
     704:   end
     705: 
     706:   def test_complex
===============================================================================
......E
===============================================================================
Error: test_range(Func): FrozenError: can't modify frozen Range: 0..0
test/tests.rb:1801:in `load'
test/tests.rb:1801:in `dump_and_load'
test/tests.rb:196:in `test_range'
     193:     if RUBY_VERSION.start_with?('1.8')
     194:       assert(true)
     195:     else
  => 196:       dump_and_load((0..3), false)
     197:       dump_and_load((-2..3.7), false)
     198:       dump_and_load(('a'...'f'), false)
     199:       t = Time.local(2012, 1, 5, 23, 58, 7)
===============================================================================
.........................
Finished in 0.029947912 seconds.
-------------------------------------------------------------------------------
150 tests, 233 assertions, 0 failures, 4 errors, 0 pendings, 0 omissions, 0 notifications
97.3333% passed
-------------------------------------------------------------------------------
```

Full build log available on: https://koji.fedoraproject.org/koji/taskinfo?taskID=59154926 see `build.log`

**Comment by mtasaka** [comment]
I may be wrong, however looks like ox firstly generates "empty" range here: https://github.com/ohler55/ox/blob/234b0916058721e0e9ca0391cb51fb333ee53488/ext/ox/obj_load.c#L623 , and next tries to modify the range like: https://github.com/ohler55/ox/blob/234b0916058721e0e9ca0391cb51fb333ee53488/ext/ox/obj_load.c#L743 , however with ruby 3.0, range is frozen https://bugs.ruby-lang.org/issues/15504 https://github.com/ruby/ruby/commit/0096d2b895395df5ab8696d3b6d444dc1b7730b6 , so this is impossible with ruby 3.0.  

A possible solution may be to recall `rb_range_new()` .

**Comment by ohler55** [comment]
Let me see if there is a better way. Thanks for running the tests.

**Comment by mtasaka** [comment]
Something like...

```
--- ox-2.14.0/ext/ox/obj_load.c.debug	2021-01-08 18:54:48.224731542 +0900
+++ ox-2.14.0/ext/ox/obj_load.c	2021-01-08 23:47:06.601753509 +0900
@@ -739,16 +739,40 @@
 		helper_stack_push(&pi->helpers, h->var, h->obj, KeyCode);
 		break;
 	    case RangeCode:
-		if (ox_beg_id == h->var) {
-		    RSTRUCT_SET(ph->obj, 0, h->obj);
-		} else if (ox_end_id == h->var) {
-		    RSTRUCT_SET(ph->obj, 1, h->obj);
-		} else if (ox_excl_id == h->var) {
-		    RSTRUCT_SET(ph->obj, 2, h->obj);
-		} else {
-		    set_error(&pi->err, "Invalid range attribute", pi->str, pi->s);
-		    return;
+		{
+		    VALUE begin, end;
+		    int excl;
+
+		    rb_range_values(ph->obj, &begin, &end, &excl);
+		    if (ox_beg_id == h->var) {
+			begin = h->obj;
+		    } else if (ox_end_id == h->var) {
+			end = h->obj;
+		    } else if (ox_excl_id == h->var) {
+			excl = RTEST(h->obj);
+		    } else {
+			set_error(&pi->err, "Invalid range attribute", pi->str, pi->s);
+			return;
+		    }
+
+		    if ((!FIXNUM_P(begin) || !FIXNUM_P(end)) && !NIL_P(begin) && !NIL_P(end)) {
+			VALUE v;
+
+			v = rb_funcall(begin, rb_intern("<=>"), 1, end);
+			if (NIL_P(v)) {
+			  if (ox_zero_fixnum == begin) { begin = end; }
+			  else if (ox_zero_fixnum == end) { end = begin; }
+			  else {
+			    set_error(&pi->err, "Invalid range attribute", pi->str, pi->s);
+			    return;
+			  }
+			}		
+		    }
+
+		    ph->obj = rb_range_new(begin, end, excl);
+
 		}
+
 		break;
 	    case KeyCode:
 		{
```

At least test seems to pass with ruby 2.7.2 and 3.0.0. I guess there is some better code :)

**Comment by ohler55** [comment]
Something like that. There are a few issues with the code but if you would like to create a PR I can point out the changes needed. Once done you will be a contributor to Ox.

**Comment by mtasaka** [comment]
Okay, then once I'll create PR.

**Comment by ohler55** [comment]
Fixed

**Comment by mtasaka** [comment]
Thank you!
