### ISSUE TITLE
Ruby 3.2 compatibility

### ISSUE THREAD

**Issue by dkam** [ohler55/ox#300]
Hello - I'm wondering if others are having problems loading Ox with Ruby 3.2? 

The problem seems to be `require 'ox/ox'`

I see another gem having [issues](https://github.com/technion/ruby-argon2/issues/56) although I'm not sure it's the same thing.

When I CD into `/Users/dkam/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ox-2.14.11/ext/ox` and run make, I can load the gem: 

```shell
➜  ox make
compiling base64.c
compiling builder.c
compiling cache.c
compiling cache8.c
compiling dump.c
compiling err.c
compiling gen_load.c
compiling hash_load.c
compiling intern.c
compiling obj_load.c
compiling ox.c
compiling parse.c
compiling sax.c
compiling sax_as.c
compiling sax_buf.c
compiling sax_hint.c
compiling slotcache.c
compiling special.c
linking shared-object ox.bundle
```

Require now works:

```ruby
irb(main):002:0> require 'ox'
/Users/dkam/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ox-2.14.11/ext/ox/ox.bundle: warning: undefining the allocator of T_DATA class Ox::Cache
=> true
```
 

Prior to manually running make, I was getting:

```ruby
irb(main):001:0> require 'ox'
<internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ox/ox (LoadError)
        from <internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/dkam/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ox-2.14.11/lib/ox.rb:79:in `<top (required)>'
        from <internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from (irb):1:in `<main>'                             
        from /home/dkam/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /home/dkam/.rbenv/versions/3.2.0/bin/irb:25:in `load'
        from /home/dkam/.rbenv/versions/3.2.0/bin/irb:25:in `<main>'
<internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ox (LoadError)
        from <internal:/home/dkam/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from (irb):1:in `<main>'                             
        from /home/dkam/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /home/dkam/.rbenv/versions/3.2.0/bin/irb:25:in `load'
	from /home/dkam/.rbenv/versions/3.2.0/bin/irb:25:in `<main>'
```

**Comment by hsbt** [comment]
I submit a quick fix for this https://github.com/ohler55/ox/pull/301

**Comment by andy-t-sp** [comment]
I am having a similar issue when running Ox on AWS Elastic Beanstalk.

Ruby 3.2.2 is included in with the Amazon Linux 2 distro, and as far as I can tell I was using the latest version of rubygems, latest version of bundler, and Ox v2.14.18.

Stacktrace:
```
=== puma startup: 2024-04-11 12:41:26 +0000 ===
[835609] - Worker 0 (PID: 835658) booted in 0.26s, phase: 0
#<Thread:0x00007fb245d3cf80 config.ru:4 run> terminated with exception (report_on_exception is true):
<internal:/usr/local/share/ruby3.2/site_ruby/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- ox/ox (LoadError)
	from <internal:/usr/local/share/ruby3.2/site_ruby/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /var/app/current/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/lib/ox.rb:82:in `rescue in <top (required)>'
	from /var/app/current/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/lib/ox.rb:79:in `<top (required)>'
	from <internal:/usr/local/share/ruby3.2/site_ruby/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/share/ruby3.2/site_ruby/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /var/app/current/lib/my_app_txn_and_msg/msg/my_app/my_app_msg.rb:3:in `<top (required)>'
        ...
	from /var/app/current/app/tests.rb:19:in `<top (required)>'
	from config.ru:7:in `require_relative'
	from config.ru:7:in `block (2 levels) in <main>'
/var/app/current/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/lib/ox.rb:80:in `require_relative': cannot load such file -- /var/app/current/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/lib/ox.so (LoadError)
	from /var/app/current/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/lib/ox.rb:80:in `<top (required)>'
	from <internal:/usr/local/share/ruby3.2/site_ruby/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/share/ruby3.2/site_ruby/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /var/app/current/lib/my_app_txn_and_msg/msg/my_app/my_app_msg.rb:3:in `<top (required)>'
        ...
	from /var/app/current/app/tests.rb:19:in `<top (required)>'
	from config.ru:7:in `require_relative'
	from config.ru:7:in `block (2 levels) in <main>'
```

I worked around the issue by building the Ox library on the server when it starts, as the OP did in his original work-around.

To do this, I added these lines to a .sh file called by a config file in the `.ebextensions` directory

`.ebextensions/install_packages.config`
```
container_commands:
  01install_packages:
    command: "bash .ebextensions/my_script.sh"
```

`.ebextensions/my_script.sh`
```
( cd /var/app/current/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/ext/ox && make )
( cd /var/app/staging/vendor/bundle/ruby/3.2.0/gems/ox-2.14.18/ext/ox && make )
``` 
One of these lines is probably superfluous, and of course, this is brittle because I've hardcoded both the ruby version and ox version numbers in my `make` lines. 

I'm just leaving this comment here in case anybody else finds themselves in a similar position.
